fun main() {
    val a = 23
    val b = 0

        val div = try { a / b } catch(ex: Exception) { 0 };  

        print(div)
}
